### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by CostaCostaCosta** [bluenote10/PandasDataFrameGUI#21]
I get this error when installing:
-----
C:\Users\ecost>conda install --offline dfgui-0.1-py27_0.tar.bz2
Fetching packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\ecost\Anaconda3  (writable)
    default environment : C:\Users\ecost\Anaconda3
       envs directories : C:\Users\ecost\Anaconda3\envs
          package cache : C:\Users\ecost\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32/  (offline)
                          https://repo.continuum.io/pkgs/free/noarch/  (offline)
                          https://repo.continuum.io/pkgs/pro/win-32/  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch/  (offline)
                          https://repo.continuum.io/pkgs/msys2/win-32/  (offline)
                          https://repo.continuum.io/pkgs/msys2/noarch/  (offline)
            config file : None
           offline mode : True

`$ C:\Users\ecost\Anaconda3\Scripts\conda-script.py install --offline dfgui-0.1-py27_0.tar.bz2`

    Traceback (most recent call last):
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\fetch.py", line 378, in download
        resp.raise_for_status()
      File "C:\Users\ecost\Anaconda3\lib\site-packages\requests\models.py", line 862, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: None for url: file:///C:/Users/ecost/dfgui-0.1-py27_0.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\cli\install.py", line 209, in install
        explicit(args.packages, prefix, verbose=not context.quiet)
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\misc.py", line 187, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Users\ecost\Anaconda3\lib\site-packages\conda\fetch.py", line 387, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 404 Client Error: None for url: file:///C:/Users/ecost/dfgui-0.1-py27_0.tar.bz2: file:///C:/Users/ecost/dfgui-0.1-py27_0.tar.bz2

-----
When I try and run the sample code, I get this error:
-----
TypeError                                 Traceback (most recent call last)
<ipython-input-3-672254b78e7f> in <module>()
----> 1 dfgui.show(df)

C:\Users\ecost\Anaconda3\lib\site-packages\dfgui\dfgui.py in show(df)
    632 
    633     app = wx.App(False)
--> 634     frame = MainFrame(df)
    635     frame.Show()
    636     app.MainLoop()

C:\Users\ecost\Anaconda3\lib\site-packages\dfgui\dfgui.py in __init__(self, df)
    583         self.page2 = ColumnSelectionPanel(nb, columns, self.page1.df_list_ctrl)
    584         self.page3 = FilterPanel(nb, columns, self.page1.df_list_ctrl, self.selection_change_callback)
--> 585         self.page4 = HistogramPlot(nb, columns, self.page1.df_list_ctrl)
    586         self.page5 = ScatterPlot(nb, columns, self.page1.df_list_ctrl)
    587 

C:\Users\ecost\Anaconda3\lib\site-packages\dfgui\dfgui.py in __init__(self, parent, columns, df_list_ctrl)
    464         self.canvas = FigureCanvas(self, -1, self.figure)
    465 
--> 466         chart_toolbar = NavigationToolbar2Wx(self.canvas)
    467 
    468         self.combo_box1 = wx.ComboBox(self, choices=columns_with_neutral_selection, style=wx.CB_READONLY)

C:\Users\ecost\Anaconda3\lib\site-packages\matplotlib\backends\backend_wx.py in __init__(self, canvas)
   1571     def __init__(self, canvas):
   1572         wx.ToolBar.__init__(self, canvas.GetParent(), -1)
-> 1573         NavigationToolbar2.__init__(self, canvas)
   1574         self.canvas = canvas
   1575         self._idle = True

C:\Users\ecost\Anaconda3\lib\site-packages\matplotlib\backend_bases.py in __init__(self, canvas)
   2737         self._active = None
   2738         self._lastCursor = None
-> 2739         self._init_toolbar()
   2740         self._idDrag = self.canvas.mpl_connect(
   2741             'motion_notify_event', self.mouse_move)

C:\Users\ecost\Anaconda3\lib\site-packages\matplotlib\backends\backend_wx.py in _init_toolbar(self)
   1598             wxc._AddTool(self, self.wx_ids, text,
   1599                         _load_bitmap(image_file + '.png'),
-> 1600                         tooltip_text)
   1601 
   1602             self.Bind(wx.EVT_TOOL, getattr(self, callback),

C:\Users\ecost\Anaconda3\lib\site-packages\matplotlib\backends\wx_compat.py in _AddTool(parent, wx_ids, text, bmp, tooltip_text)
    151                        shortHelpString=text,
    152                        longHelpString=tooltip_text,
--> 153                        kind=kind)
    154     else:
    155         if text in ['Pan', 'Zoom']:

TypeError: ToolBar.AddTool(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'int'
  overload 2: 'longHelpString' is not a valid keyword argument
  overload 3: 'longHelpString' is not a valid keyword argument
-----

Hopefully that helps!

**Comment by RobRaesemann** [comment]
I'm having the same problem

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-d26f6e45cbb1> in <module>()
      1 import dfgui
----> 2 dfgui.show(df)

/usr/local/lib/python3.6/site-packages/dfgui/dfgui.py in show(df)
    632 
    633     app = wx.App(False)
--> 634     frame = MainFrame(df)
    635     frame.Show()
    636     app.MainLoop()

/usr/local/lib/python3.6/site-packages/dfgui/dfgui.py in __init__(self, df)
    583         self.page2 = ColumnSelectionPanel(nb, columns, self.page1.df_list_ctrl)
    584         self.page3 = FilterPanel(nb, columns, self.page1.df_list_ctrl, self.selection_change_callback)
--> 585         self.page4 = HistogramPlot(nb, columns, self.page1.df_list_ctrl)
    586         self.page5 = ScatterPlot(nb, columns, self.page1.df_list_ctrl)
    587 

/usr/local/lib/python3.6/site-packages/dfgui/dfgui.py in __init__(self, parent, columns, df_list_ctrl)
    464         self.canvas = FigureCanvas(self, -1, self.figure)
    465 
--> 466         chart_toolbar = NavigationToolbar2Wx(self.canvas)
    467 
    468         self.combo_box1 = wx.ComboBox(self, choices=columns_with_neutral_selection, style=wx.CB_READONLY)

/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_wx.py in __init__(self, canvas)
   1569     def __init__(self, canvas):
   1570         wx.ToolBar.__init__(self, canvas.GetParent(), -1)
-> 1571         NavigationToolbar2.__init__(self, canvas)
   1572         self.canvas = canvas
   1573         self._idle = True

/usr/local/lib/python3.6/site-packages/matplotlib/backend_bases.py in __init__(self, canvas)
   2750         self._active = None
   2751         self._lastCursor = None
-> 2752         self._init_toolbar()
   2753         self._idDrag = self.canvas.mpl_connect(
   2754             'motion_notify_event', self.mouse_move)

/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_wx.py in _init_toolbar(self)
   1596             wxc._AddTool(self, self.wx_ids, text,
   1597                         _load_bitmap(image_file + '.png'),
-> 1598                         tooltip_text)
   1599 
   1600             self.Bind(wx.EVT_TOOL, getattr(self, callback),

/usr/local/lib/python3.6/site-packages/matplotlib/backends/wx_compat.py in _AddTool(parent, wx_ids, text, bmp, tooltip_text)
    151                        shortHelpString=text,
    152                        longHelpString=tooltip_text,
--> 153                        kind=kind)
    154     else:
    155         if text in ['Pan', 'Zoom']:

TypeError: ToolBar.AddTool(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'int'
  overload 2: 'bmpDisabled' is not a valid keyword argument
  overload 3: 'shortHelpString' is not a valid keyword argument

**Comment by baogorek** [comment]
For Python 3, I had to change the install line to 
```
conda install --offline dfgui-0.1-py36_0.tar.bz2
```
I also had to install libgtk via
```
apt-get install libgtk2.0-dev    
```
but I did get it working. It's a nice little utility. Too bad the installation's not a bit smoother.
