### ISSUE TITLE
String or Unicode type required

### ISSUE THREAD

**Issue by paulz1** [bluenote10/PandasDataFrameGUI#25]
Trying to execute some very simple code.
I have a DataFrame prepared in another rogram and stored as pickle.

So, I try ```

>>>import dfgui
>>> import pandas as pd
>>> import os
>>> 
>>> if os.path.isfile('df_all_players.df') :
...     df=pd.read_pickle('df_all_players.df')
... 
>>> dfgui.show(df)

```
and get :

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/site-packages/dfgui/dfgui.py", line 634, in show
>     frame = MainFrame(df)
>   File "/usr/lib/python2.7/site-packages/dfgui/dfgui.py", line 582, in __init__
>     self.page1 = DataframePanel(nb, df, self.status_bar_callback)
>   File "/usr/lib/python2.7/site-packages/dfgui/dfgui.py", line 268, in __init__
>     self.df_list_ctrl = ListCtrlDataFrame(self, df, status_bar_callback)
>   File "/usr/lib/python2.7/site-packages/dfgui/dfgui.py", line 73, in __init__
>     self._update_columns(self.original_columns)
>   File "/usr/lib/python2.7/site-packages/dfgui/dfgui.py", line 82, in _update_columns
>     self.InsertColumn(i, col)
>   File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_controls.py", line 4726, in InsertColumn
>     return _controls_.ListCtrl_InsertColumn(*args, **kwargs)
> TypeError: String or Unicode type required
> 

Do you ave any idea where the problem is? And how to fix it?

**Comment by bluenote10** [comment]
Hm, difficult to say without having the data. Is your data frame missing column names?

Maybe you can try to change line 82 in dfgui.py: `self.InsertColumn(i, col)` to `self.InsertColumn(i, str(col))`.
