### ISSUE TITLE
Problem with indexes

### ISSUE THREAD

**Issue by CDataScience** [bluenote10/PandasDataFrameGUI#6]
Hi, I found some strange behaviour when using string indexes. My dataframe is like this

|       | count | nan | total | unique | unique_not_nan | dtype   |
|-------|-------|-----|-------|--------|----------------|---------|
| var_0 | 3     | 0   | 3     | 2      | 2              | int64   |
| var_1 | 3     | 0   | 3     | 3      | 3              | float64 |
| var_2 | 2     | 1   | 3     | 3      | 2              | float64 |
| var_3 | 0     | 3   | 3     | 1      | 0              | float64 |
| var_4 | 1     | 2   | 3     | 2      | 1              | object  |
| var_5 | 2     | 1   | 3     | 3      | 2              | float64 |

where 
var_0 ... var_5 are the indexes of the dataframe
count to dtype are the names of the columns

when I run

dfgui.show(df)

I get the following error

>  Traceback (most recent call last):
  File "c:/data_analysis.py", line 123, in <module>
    test7()
  File "c:/data_analysis.py", line 114, in test7
    compute_statistics(df)
  File "c:/data_analysis.py", line 94, in compute_statistics
    dfgui.show(df_datos_generales)
  File "C:\Anaconda2\lib\site-packages\dfgui\dfgui.py", line 627, in show
    frame = MainFrame(df)
  File "C:\Anaconda2\lib\site-packages\dfgui\dfgui.py", line 575, in __init__
    self.page1 = DataframePanel(nb, df, self.status_bar_callback)
  File "C:\Anaconda2\lib\site-packages\dfgui\dfgui.py", line 268, in __init__
    self.df_list_ctrl = ListCtrlDataFrame(self, df, status_bar_callback)
  File "C:\Anaconda2\lib\site-packages\dfgui\dfgui.py", line 72, in __init__
    self._update_rows()
  File "C:\Anaconda2\lib\site-packages\dfgui\dfgui.py", line 98, in _update_rows
    self.df = self.df_orig.loc[self.mask, self.current_columns]
  File "C:\Anaconda2\lib\site-packages\pandas\core\indexing.py", line 1225, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Anaconda2\lib\site-packages\pandas\core\indexing.py", line 758, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "C:\Anaconda2\lib\site-packages\pandas\core\indexing.py", line 1344, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "C:\Anaconda2\lib\site-packages\pandas\core\indexing.py", line 1234, in _getbool_axis
    key = check_bool_indexer(labels, key)
  File "C:\Anaconda2\lib\site-packages\pandas\core\indexing.py", line 1698, in check_bool_indexer
    raise IndexingError('Unalignable boolean Series key provided')
pandas.core.indexing.IndexingError: Unalignable boolean Series key provided

When indexes are integer, there is no problem.

Regards

**Comment by bluenote10** [comment]
This looks like a general bug in pandas:

```python
# No string index
df = pd.DataFrame({"A": [0, 1, 2]})
df.loc[[True, True, True], :]               # works
df.loc[pd.Series([True, True, True]), :]    # works

# With string index
df = pd.DataFrame({"A": [0, 1, 2]}, index=["a", "b", "c"])
df.loc[[True, True, True], :]               # works
df.loc[pd.Series([True, True, True]), :]    # fails
```

I have created an [upstream issue](https://github.com/pandas-dev/pandas/issues/14491).

For the time being I suggest to drop the index, or you can toy around with modifying the code to use an `np.array` (don't have the time right now to fully test it).

**Comment by bluenote10** [comment]
Well, turns out it is just a Pandas ugliness...
